# Generated by Django 5.1.1 on 2024-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alumno_apellido_asistencia_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='sala',
            field=models.CharField(default='Sala por asignar', max_length=50),
        ),
    ]
