# Generated by Django 5.1.1 on 2024-10-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asistencia_alumnos_ausentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.AddField(
            model_name='curso',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alumno'),
        ),
    ]
