# Generated by Django 5.1.1 on 2024-10-14 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asistencia_alumnos_ausentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
