# Generated by Django 5.1.1 on 2024-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_calificacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(),
        ),
    ]
