# Generated by Django 4.1.8 on 2024-10-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_curso_alumnos_curso_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumno',
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='core.alumno'),
        ),
    ]
