# Generated by Django 4.1.8 on 2024-10-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_curso_alumno_curso_alumnos'),
        ('core', '0008_alter_calificacion_fecha_alter_calificacion_nota'),
    ]

    operations = [
    ]
