# Generated by Django 5.1.1 on 2024-10-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20241014_1906'),
        ('core', '0010_apoderado_alumno_apoderado'),
    ]

    operations = [
    ]
