# Generated by Django 5.1.1 on 2024-10-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20241015_1555'),
        ('core', '0011_merge_20241015_1610'),
    ]

    operations = [
    ]
