# Generated by Django 5.1.1 on 2024-10-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20241015_1618'),
        ('core', '0012_merge_20241015_1728'),
    ]

    operations = [
    ]
