# Generated by Django 5.1.1 on 2024-10-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20241016_1631'),
        ('core', '0013_merge_20241017_1612'),
    ]

    operations = [
    ]
