# Generated by Django 5.1.1 on 2024-10-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alumno_estado_admision'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_inscritos', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado_admision',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='cursos_asignados', to='core.alumno'),
        ),
    ]
