# Generated by Django 5.1.1 on 2024-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alumno_curso_alter_alumno_estado_admision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado_admision',
            field=models.CharField(max_length=50),
        ),
    ]
