# Generated by Django 5.1.1 on 2024-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_alumno_apellido_alter_alumno_estado_admision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado_admision',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
