# Generated by Django 5.1.1 on 2024-10-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_alumno_apellido_alter_alumno_estado_admision'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
