# Generated by Django 5.1.1 on 2024-10-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_informefinanciero'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alumnos', models.IntegerField()),
                ('promedio_notas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promedio_asistencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
