# Generated by Django 5.1.1 on 2024-10-27 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_firma',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='contrato',
            name='alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='core.alumno'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
