# Generated by Django 5.1.1 on 2024-11-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_asismatricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='asisfinanza',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistentes_finanzas', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='asismatricula',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistentes_matricula', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='curso',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='director',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directores', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='informe',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='informeacademico',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes_academicos', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='informefinanciero',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes_financieros', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='core.establecimiento'),
        ),
        migrations.AddField(
            model_name='registroacademico',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_academicos', to='core.establecimiento'),
        ),
    ]
