# Generated by Django 5.1.1 on 2024-11-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_notificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('calificacion_baja', 'Calificación Baja'), ('asistencia', 'Asistencia')], default='calificacion_baja', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='apoderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apoderado'),
        ),
    ]
