# Generated by Django 5.1.1 on 2024-11-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profesor_asignatura_cursoalumno'),
        ('core', '0027_rename_fecha_notificacion_fecha_creacion_and_more'),
    ]

    operations = [
    ]
