# Generated by Django 5.1.1 on 2024-11-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bitacoraclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraclase',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
