# Generated by Django 5.1.3 on 2024-11-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_alumno_curso'),
        ('core', '0030_bitacoraclase_observaciones'),
    ]

    operations = [
    ]
