# Generated by Django 5.1.3 on 2024-11-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subdirector'),
        ('core', '0031_merge_20241106_1902'),
    ]

    operations = [
    ]
