# Generated by Django 5.1.3 on 2024-11-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subdirector'),
        ('core', '0032_establecimiento_alumno_establecimiento_and_more'),
    ]

    operations = [
    ]
